micronaut:
  application:
    name: covidApiCache
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  http:
    services:
      covid-19-api:
        url: https://api.covid19api.com
    client:
      log-level: debug
netty:
  default:
    allocator:
      max-order: 3
